# [[docs]]
#   name = "Prologue"
#   weight = 10
#   identifier = "prologue"
#   url = "/docs/prologue/"

# [[docs]]
#   name = "Help"
#   weight = 60
#   identifier = "help"
#   url = "/docs/help/"

# [[docs]]
#   name = "Lorem"
#   weight = 70
#   identifier = "lorem"
#   url = "/docs/lorem/"

[[guide]]
  name = "Lorem"
  weight = 10
  identifier = "lorem"
  url = "/guide/lorem/"

[[tutorial]]
  name = "Lorem"
  weight = 10
  identifier = "lorem"
  url = "/tutorial/lorem/"

[[main]]
  name = "Docs"
  url = "/docs/guides/example-guide/"
# url = "/docs/1.0/prologue/introduction/"
  weight = 10

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 30

[[social]]
  name = "Nuget"
  pre = "<svg width=\"20px\" height=\"20px\" viewBox=\"0 0 512 512\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"><defs><polygon id=\"path-1\" points=\"0 46.021103 0 3.7002935 84.6521577 3.7002935 84.6521577 88.3419125 0 88.3419125\"></polygon></defs><g id=\"Symbols\" stroke=\"none\" stroke-width=\"1\" fill=\"none\" fill-rule=\"evenodd\"><g id=\"nuget\"><g id=\"Global/Logo\" transform=\"translate(0.000000, 6.000000)\"><path d=\"M374.424959,454.856991 C327.675805,454.856991 289.772801,416.950177 289.772801,370.196324 C289.772801,323.463635 327.675805,285.535656 374.424959,285.535656 C421.174113,285.535656 459.077116,323.463635 459.077116,370.196324 C459.077116,416.950177 421.174113,454.856991 374.424959,454.856991 M205.565067,260.814741 C176.33891,260.814741 152.657469,237.109754 152.657469,207.901824 C152.657469,178.672728 176.33891,154.988907 205.565067,154.988907 C234.791225,154.988907 258.472666,178.672728 258.472666,207.901824 C258.472666,237.109754 234.791225,260.814741 205.565067,260.814741 M378.170817,95.6417786 L236.886365,95.6417786 C164.889705,95.6417786 106.479717,154.057639 106.479717,226.082702 L106.479717,367.360191 C106.479717,439.40642 164.889705,497.77995 236.886365,497.77995 L378.170817,497.77995 C450.209803,497.77995 508.577466,439.40642 508.577466,367.360191 L508.577466,226.082702 C508.577466,154.057639 450.209803,95.6417786 378.170817,95.6417786\" id=\"Fill-12\" fill=\"#004880\" fill-rule=\"evenodd\"></path><mask id=\"mask-2\" fill=\"white\"><use xlink:href=\"#path-1\"></use></mask><g id=\"Clip-15\"></g><path d=\"M84.6521577,46.0115787 C84.6521577,69.3990881 65.6900744,88.3419125 42.3260788,88.3419125 C18.9409203,88.3419125 0,69.3990881 0,46.0115787 C0,22.6452344 18.9409203,3.68124485 42.3260788,3.68124485 C65.6900744,3.68124485 84.6521577,22.6452344 84.6521577,46.0115787\" id=\"Fill-14\" fill=\"#004880\" fill-rule=\"evenodd\" mask=\"url(#mask-2)\"></path></g></g></g></svg>"
  url = "https://www.nuget.org/packages?q=efbox"    
  weight = 30

[[footer]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 10

# [[footer]]
#   name = "Terms of Service"
#   url = "/terms/"
#   weight = 20
